### ISSUE TITLE
Provide better click-area for signs

### ISSUE THREAD

**Issue by afucher** [AstroDraw/AstroChart#6]
_Issue moved from [old repo](https://github.com/Kibo/AstroChart/issues/29) created by @akamud_

We're trying to implement a feature on our app that depends on the user clicking on the symbols (planets, cusps, signs). We do this using this code:

```css
svg g[id*="astrology-radix-planets-"],
svg g[id*="astrology-radix-cusps-"],
svg g[id*="astrology-radix-signs-"] {
    pointer-events: all;
    cursor: pointer;
}
```

It works, but some symbols don't have a bounding box, which makes the click very difficult.
You can see this behaviour here (I've zoomed in so it is easier to notice the problem):

![astrochart](https://user-images.githubusercontent.com/954102/97082880-38d25500-15e3-11eb-96c8-6965acaa4404.gif)

Notice the Scorpio symbol has a "bounding box", so it is clickable through all its area. The same isn't true for the Libra sign, with the way it is drawn, I have to click exactly on its stroke paths, which is very difficult with no zoom, as you can imagine. This makes clicking very erratic.

### Workaround

As a workaround, we've added a transparent `rect` for all the signs, like this:

```js
	function createRectForClick(x, y, width, height) {
		var rect = document.createElementNS(context.root.namespaceURI, 'rect')
		rect.setAttribute('x', x - astrology.SIGNS_STROKE)
		rect.setAttribute('y', y - astrology.SIGNS_STROKE)
		rect.setAttribute('width', width)
		rect.setAttribute('height', height)
		rect.setAttribute('fill', 'transparent')
		return rect
	}
```

This makes the whole sign area clickable again.

Would you be interested in fixing this behaviour? I could open a PR.
